### ISSUE TITLE
undefined reference to `_sbrk_r

### ISSUE THREAD

**Issue by gnih** [Imroy/pubsubclient#2]
Hi,

I encounter "undefined reference to `_sbrk_r" error with arduino ide 1.6.1 and 1.6.3

Missing hard coded path?

![pubsubmqtterror](https://cloud.githubusercontent.com/assets/698976/7630471/94fb5fb2-fa36-11e4-8d89-ca23bae2d1ec.png)

**Comment by Imroy** [comment]
This is a problem that has been fixed in the Arduino-ESP8266 port (see esp8266/Arduino#11), but there is no recent build. The maintainer(s) is hoping to get a new release out this week or next week (esp8266/Arduino#188). Until then, you can build your own version from Git (what I do) or maybe try Appveyor - https://ci.appveyor.com/project/igrr/Arduino.

**Comment by gnih** [comment]
Thank you for your quick reply!
Have a nice day,
Kind regards,
G.

2015-05-14 14:28 GMT+02:00 Ian Tester <notifications@github.com>:

**Comment by jeffryr** [comment]
It also works with Arduino-1.6.4 plus the Adafruit ESP8266/Huzzah plugin.  I suspect it would work with Sandeep Mistry's addon, I see he now has a 0.0.5 release but I haven't personally tried that one.  I do all of my builds on Linux BTW, don't know what the status is on Windows or OSX.
